import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Accordion from "@/Components/Basic/Accordion/Accordion";
import FAQ from "@/Components/common/FAQ/FAQ";
import FeatureStack from "@/Components/common/FeatureStack/FeatureStack";
import { CustomCarousel } from "@/Components/common/CustomCarousel/CustomCarousel";
import styled from "styled-components";
import CMSwitch from "@/Components/Basic/Switch/Switch";
import Carousel from "@/Components/Basic/MultiItemCarousel";
import Tabs from "@/Components/Basic/Tabs/Tabs";
import ImageWithQuote from "@/Components/Basic/ImageWithQuote/ImageWithQuote";
import CarouselContinue from "@/Components/Basic/CarouselContinue";
import CarouselContinue2 from "@/Components/Basic/CarouselContinue2";
import CarouDD from "@/Components/Basic/CarouDD";
import TryNumberOne from "@/Components/Basic/TryNumberOne";
import TryNumberTwo from "@/Components/Basic/TryNumberTwo";
import TryNumberThree from "@/Components/Basic/TryNumberThree";
import TryNumberFour from "@/Components/Basic/TryNumberFour";
import MasonryLayout from "@/Components/Basic/MasonryLayout";

const H1 = styled.h1`
  text-align: center;
  margin: 0;
  padding-bottom: 10rem;
`;
const Flex = styled.div`
  display: flex;
`;
interface ItemInterface {
  size: any;
}
const Item = styled.div<ItemInterface>`
  color: white;
  font-size: 2rem;
  text-transform: capitalize;

  width: ${({ size }) => `${size}rem`};
  height: ${({ size }) => `${size}rem`};

  display: flex;

  align-items: center;
  justify-content: center;
`;

const HorizontalCenter = styled(Flex)`
  justify-content: center;
  margin-left: auto;
  margin-right: auto;

  max-width: 25rem;
`;
const Container = styled.div`
  height: stretch;
  width: 100%;

  background: #ecf0f1;
`;
const inter = Inter({ subsets: ["latin"] });
const colors = [
  "#f1c40f",
  "#f39c12",
  "#e74c3c",
  "#16a085",
  "#2980b9",
  "#8e44ad",
  "#2c3e50",
  "#95a5a6",
];

const numbersArray = Array.from(Array(10).keys()).map((number) => (
  <Item size={5} style={{ color: "black" }} key={number}>
    {number}
  </Item>
));

const colorsArray = colors.map((color) => (
  <Item
    size={20}
    style={{ background: color, borderRadius: "20px", opacity: 0.9 }}
    key={color}
  >
    {color}
  </Item>
));
const slides = [
  {
    id: 1,
    image: "https://via.placeholder.com/900x300/c69/f9c/?text=1",
    caption: "Slide 1",
  },
  {
    id: 2,
    image: "https://via.placeholder.com/900x300/c69/f9c/?text=2",
    caption: "Slide 2",
  },
  {
    id: 3,
    image: "https://via.placeholder.com/900x300/c69/f9c/?text=3",
    caption: "Slide 3",
  },
  {
    id: 4,
    image: "https://via.placeholder.com/900x300/c69/f9c/?text=4",
    caption: "Slide 4",
  },
  {
    id: 5,
    image: "https://via.placeholder.com/900x300/c69/f9c/?text=5",
    caption: "Slide 5",
  },
  {
    id: 6,
    image: "https://via.placeholder.com/900x300/c69/f9c/?text=6",
    caption: "Slide 6",
  },
  {
    id: 7,
    image: "https://via.placeholder.com/900x300/c69/f9c/?text=7",
    caption: "Slide 7",
  },
];
const slidesd = [<div>1</div>, <div>3</div>, <div>1</div>];
interface SlideData {
  order: number;
  text: string;
}
const sslides: SlideData[] = [
  { order: -1, text: "6" },
  { order: 0, text: "1" },
  { order: 1, text: "2" },
  { order: 2, text: "3" },
  { order: 3, text: "4" },
  { order: 4, text: "5" },
];
export default function Home() {
  return (
    <>
      <Head>
        <title>uiCollections</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{ width: "100%", height: "100vh", padding: " 0", margin: "0" }}
      >
        <CMSwitch />
        <FAQ />
        {/* <Container>
          <H1>Easy Carousel</H1>
          <HorizontalCenter>
            <CustomCarousel>{colorsArray}</CustomCarousel>
          </HorizontalCenter>

          <HorizontalCenter>
            <CustomCarousel>{numbersArray}</CustomCarousel>
          </HorizontalCenter>
        </Container> */}
        {/* <FeatureStack /> */}
        {/* <TryNumberFour /> */}
        <Carousel slides={slides} />
        <FAQ />
        {/* <CarouselContinue />
        <CarouselContinue2 slides={slides} /> */}
        {/* <TryNumberOne slides={slides} />
        <Tabs />
        <ImageWithQuote /> */}
        Two
        <MasonryLayout />
        {/* <TryNumberTwo slides={slides} />
        <TryNumberThree /> */}
        <FAQ />
        <FAQ />
      </main>
    </>
  );
}
